### ISSUE TITLE
Business Logic should be moved to services or lib

### ISSUE THREAD

**Issue by abhinavmsra** [gipsy/nimbl3_scraper#2]
In current implementation, scraping logic are inside `Report`  model. Models should only act as an interface between application and database and not implement core application logic.

**Comment by gipsy** [comment]
@abhinavmsra 
good point, will move it to more appropriate place.

**Comment by gipsy** [comment]
@abhinavmsra 
I've moved business logic to services. Please take a look when you got a chance.

**Comment by abhinavmsra** [comment]
@gipsy any specific reasons behind choosing `Aldous`? Couldnt it be done it a more simplified way?

**Comment by gipsy** [comment]
@abhinavmsra 
well, I've used this approach to adhere best practices like described on this article https://code.tutsplus.com/tutorials/service-objects-with-rails-using-aldous--cms-23689

**Comment by olivierobert** [comment]
@gipsy Similarly to what Abhinav mentioned, I think the service pattern can be used with POROs. 

A basic service would look like the following:

```ruby
class Service 
   att_accessor :attr_1

   de initialize
   ...
   end
   
   def call
   ...
   end

   private
   ...
end 
```

Resorting to a gem to build something like this seems not adapted. 

<img width="1008" alt="aldous___rubygems_org___your_community_gem_host" src="https://user-images.githubusercontent.com/696529/29778129-7eb5d8ae-8c38-11e7-90f2-9f4eac5f4cb8.png">

Also when adding a dependency to the core, one should always check some basic requirements: 
- is the gem widely used? On rubygems, it shows a max of 12K downloads which is pretty low
-  is the project still maintained? There has not been any update for two years

**Comment by olivierobert** [comment]
@gipsy If you are interested in the kind of architecture proposed by Aldous, then you should check [Trailblazer](https://github.com/trailblazer/trailblazer) or [dry-web-roda](https://github.com/dry-rb/dry-web-roda)
